### ISSUE TITLE
File read and write after every operation?

### ISSUE THREAD

**Issue by devat19** [patrickmoffitt/local-sqlite-example#3]
I don't think this issue is related to your repo, but related to sql.js.
I am using sql.js and can't fathom the fact that after every write, you have to do a complete write to the parent file. Am i wrong or missing something? Is it normal in sqlite?

**Comment by patrickmoffitt** [comment]
Can you please provide a code example? Which of the [API methods](https://sqlite.org/c3ref/io_methods.html) are you referring to?
Just to guess at what you're meaning...It's true that when using TRANSACTIONS you have to COMMIT or ROLLBACK.

**Comment by patrickmoffitt** [comment]
Not an issue.
