### ISSUE TITLE
Blank UI

### ISSUE THREAD

**Issue by elkizana** [patrickmoffitt/local-sqlite-example#4]
![rsz_screenshot_from_2020-09-21_16-07-18](https://user-images.githubusercontent.com/53874333/93784663-2a300100-fc25-11ea-8af7-ecd645fb865b.png)
I'm under Ubuntu 20.04

**Comment by patrickmoffitt** [comment]
Please look in the console for messages. Press Command+Option+J (Mac) or Control+Shift+J (Windows, Linux, Chrome OS). Add any messages you find to this issue. Thanks.

**Comment by Barbarosse** [comment]
Thanks @patrickmoffitt  I typed the shortcut in the window nothing showed up.

**Comment by elkizana** [comment]
Thanks @patrickmoffitt. This is what I get : 
` TypeError: Cannot read property 'app' of undefined
    at renderer.js:5`

**Comment by patrickmoffitt** [comment]
Added ```enableRemoteModule: true``` to ```webPreferences``` in **main.js** to address a [breaking change in Electron 10](https://www.electronjs.org/docs/breaking-changes) wherein the remote module is now disabled by default.
![Screen Shot 2020-09-22 at 9 12 36 AM](https://user-images.githubusercontent.com/10067873/93897148-be4ea680-fcbf-11ea-9c76-c2387f1a4dc4.jpg)
