### ISSUE TITLE
Where does the Sqlite database goes ? 

### ISSUE THREAD

**Issue by elkizana** [patrickmoffitt/local-sqlite-example#5]
@patrickmoffitt Thank you very much for your contributions. 
After the saving where can we find the created database ? 
Also Is possible to contact you for help purpose not for reporting, it would much appreciated because I'm not good in coding.
Thanks.

**Comment by patrickmoffitt** [comment]
The SQLite database is in the folder returned by electron.app.getPath('userData'). The result of this expression varies by platform.
